Khushi-Nigam/jobportal

README.md

I have added the file/folder structure till 2 levels (just after the root directory) in the README.
Let me know if any changes are needed.
Also, I noticed that the folder inside `adminapp` is named `static/assests` — it might be a typo or issue. I think it should be `assets` inside the `static` folder.
This PR fixes issue #9

Added file structure to README

---

README.md

As discussed under issue #9 , I have converted Technologies Used into a table

Converted Technologies Used into a table

---

jobapp/templates/login.html
jobapp/templates/parent.html

Fixes #8
This PR includes a complete redesign of the login page UI to improve user experience and visual appeal.
OLD -------------------------------------------------------------- NEW

Login UI redesign with cleanup (#8)

---

jobapp/templates/index.html
jobapp/templates/parent.html
jobapp/templates/services.html

Changes Made:
- Updated "index.html" and "parent.html"  and "service.html" templates
- Improved header layout for better responsiveness
- Added hover effect in the service page cards
- Added styling enhancements to the footer section
- Minor spacing and alignment fixes
Related Issues:
- Closes #10 
Additional Notes:
- Tested on desktop and mobile views
- Let me know if any adjustments are needed

Updated header and footer and added hover effects to service cards

---

employer/views.py
jobapp/utils.py
jobportal/settings.py
jsapp/views.py

Create email notification feature #37

Emailnotification

---

.gitignore

Updated the git ignore file so when pushing code to repo and merging it won't cause any conflicts further

fix/.gitignore #58

---

jobapp/templates/login.html

Resolved errors preventing the Django project from running locally. Added proper setup steps and fixed configuration for smooth development. Closes #8.

Fixed Django setup and project run issues 

---

jobapp/templates/employer.html

Issue #26 
This pull request updates the UI of the employer registration form to match the design and styling of the jobseeker registration form.
✅ What was changed:
- Matched form layout with consistent padding, font styling, and spacing
- Applied same input and select styles as jobseeker registration
- Unified background color, card appearance, and font
- Reorganized HTML structure for clarity and maintainability
- Preserved all form fields and validation messages
🎯 Goal:
Improve UI consistency across the platform and align employer and jobseeker registration pages.

#issue 26 / 39 Redesign employer registration form UI to match jobseeker 

---

jobapp/templates/login.html

added linkedin button as new login feature

---

employer/models.py
employer/templates/employerparent.html
employer/views.py
jobapp/templates/employer.html
jobapp/views.py
jsapp/jsappurls.py
jsapp/views.py

issue #76
1. Updated the login logic: 
Login now checks usertype (jobseeker/employer) from the database to redirect users correctly.
2. Implemented proper redirection after login, based on the verified user role:
  • jobseeker → /jsapp/jshome
  • employer → /employer/employerhome

BUG FIX - Make Login Button Functional #76

---

jobapp/templates/index.html
jobapp/templates/parent.html

As said in the issue i was assigned to,I had fixed the header section by removing the top navbar and secondly removed all the photos in latest job section and lighten the background colour of that section ,changed the text colour to black so that it goes well with the background colour,aligned all the timings.
Attaching the screenshot after removing the top navbar:
@issue no:#71

fixed the latest job section and header section

---

jobapp/templates/services.html

Improved the layout of the YouTube video section on the /services page by applying a CSS Grid layout to the .vid-container.
Issue fix: #94 
Changes I made:
1. Converted the video section to a display: grid layout
2. Arranged videos in 3 columns using grid-template-columns: 1fr 1fr 1fr
3. Used place-items: center to center the content inside each grid cell
4. Added gap: 10px for consistent spacing
5. Applied margin: 0 auto to center the container itself

Rearranged YouTube Videos Using Grid Layout

---

jobapp/jobappurls.py
jobapp/templates/index.html
jobapp/views.py
jobportal/settings.py

- Fixed AttributeError in `search_jobs` view
- Updated `views.py` to handle posteddate as string
- Added search URL pattern to `urls.py`
- Implemented AJAX + loading spinner in `index.html`
- Refactored job filtering logic

Fix AJAX search and enhance job search experience

---

jobapp/templates/index.html

This pull request addresses issue #123 by updating the shape and color of text and button in index.html

Update index.html #123

---

jobapp/templates/blog.html

This pull request addresses issue #123 by updating the shape and color of text and button in blog.html

Update blog.html #123

---

jsapp/templates/jsparent.html

Fixed all the issues with the code as well as made improvements in the nav section
https://github.com/user-attachments/assets/5bdbc11c-eaee-4f28-a5cf-5900d4c40e6d

Made improvements and solved bugs of issue #99

---

jobapp/templates/index.html

i have removed the content of ui-fixes from the home page.
fixed issue #129

Removed the ui-fixes in the home page

---

jobapp/templates/parent.html

enhanced the footer section by increasing the font size of logos of social media,content ,changing the colour of the content and the hover effect.
Fixed issue #128

Enhanced the footer section 

---

jobapp/templates/jobseeker.html

Fixes #140 — Adds password strength checks, validates phone numbers, and restricts resume uploads to PDF/DOC/DOCX formats, showing errors for unsupported files.

 Improve Registration Validation and Restrict Resume Uploads

---

jobapp/templates/jobseeker.html

This pull request addresses issue #102 by checking password is of minimum length of 6

Update jobseeker.html #102

---

jobapp/templates/aboutus.html
jobapp/templates/parent.html

Please review and drop your feedback. I would gladly change anything you don't like.

Added navbar styling as inline styling and also commented overflow-x in container in aboutus.

---

employer/templates/employerparent.html
jsapp/templates/jsparent.html

Fixed navigation issues for Employer and Jobseeker profile management buttons.
Ensured both redirect correctly to their respective profile pages.
Fixes #154

Fix: Profile Management Button for Employer & Jobseeker

---

jobapp/templates/aboutus.html
jobapp/templates/parent.html
jobapp/templates/services.html

Made a minor update on the service file. Please review and give your feedback.
Solving issue #159

making text clear on about-us page in the footer

---

jsapp/templates/changepassword.html

This pull request addresses issue #179, to improve the UI of changepassword page.

Update changepassword.html #179

---

jobapp/templates/aboutus.html
jobapp/templates/blog.html
jobapp/templates/contactus.html
jobapp/templates/index.html
jobapp/templates/services.html

This pull request fixes the issue where the Register dropdown button was not consistently showing or working across all pages.
Updated the header/navbar template to ensure the Register dropdown appears on all pages.
Fixed links for Employer, Job Seeker, and Administrator registration to work correctly.
Verified that the dropdown styling and functionality are consistent across different screen sizes.
This ensures that users can now access the registration options from any page without issues.
fixes #180

fix: register btn working on all pages

---

jobapp/templates/employer.html

This PR fixes the layout of the Employer Registration form.This improves readability and enhances the overall user experience.
fixes: #182

fix: improve layout of checkbox and submit button of employeer.

---

jobapp/templates/login.html
myenv/pyvenv.cfg

Recently I identified the issue of login page where I was not able to see my password so decided to fix here is fix for it 
Here is proof as image

login toggle button to see password solved

---

jobapp/templates/index.html

This PR implements a redesigned hero section on the homepage to improve user experience, engagement, and visual appeal.
Fixes #219 
---
---
- Typography: Changed to bold, large, and more well-structured subheading.
- CTA Buttons: New action buttons like Browse Services and Post a Job added.
- Background: Polished gradient and some subtle shapes added for sophistication.
- Responsive Design: Improved design for smartphones and tablets.
---
---
---
If you have any suggestions or feedback, I’d be happy to improve it further.
Thank you for the opportunity to contribute as part of GSSoC '25! 🙌

Redesign Hero Section for Modern UX and Engagement

---

.gitignore
jobapp/templates/apply.html
jobapp/templates/blog.html
jobapp/templates/contactus.html
jobapp/templates/services.html

Ma’am, I solved my issue "Navbar not opening on 'Apply Now' page #210", but you closed it saying it was already working fine. Ma’am, please check it once again — it’s still not working properly.
https://github.com/user-attachments/assets/570a2051-5d84-4a09-b994-21a254a09c52
I have resolved this issue, you can go ahead and merge it.
https://github.com/user-attachments/assets/e2f8aed8-8113-4237-8037-a0b4d627083e

Navbar not opening issue

---

jobapp/templates/index.html

This PR fixes Issue #85 by adding a **Dark Mode Toggle** feature to improve user experience and accessibility.
- Added a Dark Mode toggle button.
- Implemented theme switching (light ↔ dark).
- Ensured components adapt correctly in both modes.
Closes #85

Feature: Add Dark Mode Toggle for Better UX Accessibility

---

.github/workflows/django-validator.yml

#214 This PR introduces a basic CI workflow using GitHub Actions.
It automatically runs python manage.py check on all pull requests targeting the master branch to ensure basic Django syntax and configuration are correct. The workflow will exit with an error code if any fatal problems are detected, which will mark the check as failed.
Why its important?
This workflow is crucial as it automatically validates all contributions, protecting the master branch from errors and providing immediate feedback.

Added Github Actions ci to check django syntax and configuration

---

.github /pull_request_template.md
README.md

Description
This PR adds a Contributors section to the README.md to recognize and showcase all contributors, making the repository more welcoming for new contributors.
Current Problem
The README.md currently lacks a Contributors section to recognize contributors and guide new ones.
Proposed Solution
Add a Contributors section at the end of README.md
Include an auto-generated contributor badge via [contrib.rocks](https://contrib.rocks/)
Update Table of Contents to include this new section
Keep all existing content intact and improve formatting where necessary
Benefits
Recognizes contributors and shows appreciation
Makes the repository more welcoming for new contributors
Improves documentation readability and structure
Close issue #242

Add Contributors Section to README.md
